using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using TMPro;
using Photon.Pun;

public class WaterGunShot : MonoBehaviourPunCallbacks
{
    //ï¿½ï¿½ï¿½Iï¿½uï¿½Wï¿½Fï¿½Nï¿½g
    [SerializeField] GameObject Water;

    //ï¿½ï¿½ï¿½ËŠÔŠu
    const float INTERVAL = 5.5f;

    //ï¿½ï¿½ï¿½ËŠÔŠuï¿½Ò‚ï¿½ï¿½ï¿½ï¿½ï¿½
    float m_FireInterval = 0;

    //ï¿½ï¿½ï¿½ï¿½
    const float DIRECTION_1 = -3;
    const float DIRECTION_2 = 5;

    //ï¿½ï¿½ï¿½ï¿½ï¿½ÌƒJï¿½Eï¿½ï¿½ï¿½g
    float m_DirectionCount = 0;

    //ï¿½ï¿½ï¿½ÌˆĞ—ï¿½
    int m_WaterPower = 3;

    //ï¿½ï¿½ï¿½ï‚·ï¿½é…ï¿½Ì—ï¿½
    const int WATER_COST = 2;

    //ï¿½Gï¿½tï¿½Fï¿½Nï¿½g
    [SerializeField] GameObject m_Effect;

    //ï¿½Qï¿½[ï¿½ï¿½ï¿½ï¿½ï¿½Iï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Ç‚ï¿½ï¿½ï¿½
    private bool b_isGameFinish;

    private GameObject SettingUIManagerObj;

    // Start is called before the first frame update
    void Start()
    {
        m_Effect.SetActive(false);
        b_isGameFinish = false;
        SettingUIManagerObj = GameObject.Find("SettingUIManager");
    }

    // Update is called once per frame
    void Update()
    {        
    }
    private void FixedUpdate()
    {
        if (photonView.IsMine)
        {
            if (b_isGameFinish == false && SettingUIManagerObj.GetComponent<SettingUIManager>().GetMenuMode() == false)
            {
                //ï¿½ï¿½ï¿½ËŠÔŠuï¿½Ò‚ï¿½ï¿½ï¿½ï¿½Ô‚ï¿½0ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½
                if (m_FireInterval <= 0)
                {
                    //ï¿½}ï¿½Eï¿½Xï¿½ï¿½ï¿½ï¿½ï¿½Nï¿½ï¿½ï¿½bï¿½Nï¿½ï¿½ï¿½Ä‚ï¿½ï¿½ï¿½ï¿½ ï¿½Ü‚ï¿½ï¿½Í@RBï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Ä‚ï¿½ï¿½ï¿½ï¿½
                    if (Input.GetMouseButton(0) || Input.GetKey("joystick button 5"))
                    {
                        //ï¿½ï¿½ï¿½Ì—Ê‚ï¿½ï¿½æ“¾
                        AmountOfWater amountOfWater = gameObject.GetComponent<AmountOfWater>();
                        int check = amountOfWater.GetAmountOfWater();

                        if (check > 0)
                        {
                            //ï¿½ï¿½ï¿½ï¿½
                            photonView.RPC(nameof(GunShot), RpcTarget.All);

                            //ï¿½Gï¿½tï¿½Fï¿½Nï¿½gï¿½\ï¿½ï¿½
                            m_Effect.SetActive(true);

                            //ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ç‚·
                            amountOfWater.DownAmountOfWater(WATER_COST);
                        }
                        else
                        {
                            //ï¿½Gï¿½tï¿½Fï¿½Nï¿½gï¿½ï¿½\ï¿½ï¿½
                            m_Effect.SetActive(false);
                            Debug.Log("Norn Water");
                        }
                    }
                    else
                    {
                        //ï¿½Gï¿½tï¿½Fï¿½Nï¿½gï¿½ï¿½\ï¿½ï¿½
                        m_Effect.SetActive(false);
                    }
                }
                else
                {
                    //ï¿½Cï¿½ï¿½ï¿½^ï¿½[ï¿½oï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ç‚·
                    m_FireInterval -= Time.deltaTime;
                }
            }
        }
    }

    [PunRPC]
    private void GunShot()
    {
        //ï¿½ï¿½ï¿½W
        Vector3 pos = this.gameObject.transform.position;
        //ï¿½ï¿½ï¿½ï¿½ï¿½ÌƒIï¿½uï¿½Wï¿½Fï¿½Nï¿½g
        GameObject myobject = this.gameObject;
        //ï¿½ï¿½]ï¿½pï¿½x
        Quaternion keeprotation = this.gameObject.transform.rotation;

        //ï¿½ï¿½ï¿½Ëƒpï¿½^ï¿½[ï¿½ï¿½
        if (m_DirectionCount == 10)
        {
            myobject.transform.Rotate(0, DIRECTION_1, 0);
            m_DirectionCount = 0;
        }
        else if (m_DirectionCount == 6 || m_DirectionCount == 8)
        {
            myobject.transform.Rotate(0, DIRECTION_2, 0);
            m_DirectionCount++;
        }
        else
        {
            myobject.transform.Rotate(0, 0, 0);
            m_DirectionCount++;
        }


        // Cubeï¿½vï¿½ï¿½ï¿½nï¿½uï¿½ï¿½ï¿½ï¿½ï¿½ÉAï¿½Cï¿½ï¿½ï¿½Xï¿½^ï¿½ï¿½ï¿½Xï¿½ğ¶ï¿½ï¿½A
        GameObject waterobject = Instantiate(Water, new Vector3(pos.x, pos.y, pos.z), myobject.transform.rotation);

        //IDï¿½ï¿½ï¿½í‚½ï¿½ï¿½ï¿½@
        waterobject.GetComponent<WaterMove>().Init(photonView.OwnerActorNr);

        //ï¿½ï¿½ï¿½ÌˆĞ—Í‚ï¿½ï¿½wï¿½ï¿½
        waterobject.GetComponent<WaterMove>().SetWaterPower(m_WaterPower);

        //ï¿½Cï¿½ï¿½ï¿½^ï¿½[ï¿½oï¿½ï¿½ï¿½Zï¿½bï¿½g
        m_FireInterval = INTERVAL * Time.deltaTime;

        //ï¿½ï¿½]ï¿½pï¿½ï¿½ß‚ï¿½
        this.gameObject.transform.rotation = keeprotation;
    }

    public void SetIsGameFinish(bool isGameFinish)
    {
        b_isGameFinish = isGameFinish;
    }
}
