using System.Collections;
using System.Collections.Generic;
using UnityEngine;

using Photon.Pun;
using TMPro;
public class PlayerController : MonoBehaviourPunCallbacks
{
    public float speed = 3f;
    public float jumpPower = 3f;
    public Vector3 localGravity = new Vector3(0.0f, -9.8f, 0.0f);

    private Rigidbody rb;
    private float horizontal, vertical;
    private Vector3 moveDirection = Vector3.zero;
    private bool isGround;
    private bool jumpFlag = false;
    private TestHeat.PLAYER_STATE playerState = TestHeat.PLAYER_STATE.ARIVE;


    // Start is called before the first frame update
    void Start()
    {
        //Rigidbodyï¿½ï¿½ï¿½æ“¾ï¿½ï¿½ï¿½Cï¿½ï¿½]ï¿½ï¿½ï¿½È‚ï¿½ï¿½æ‚¤ï¿½ÉŒÅ’ï¿½
        rb = GetComponent<Rigidbody>();
        //rb.constraints = RigidbodyConstraints.FreezeRotation;

        rb.useGravity = false;
    }

    // Update is called once per frame
    void Update()
    {
        if (photonView.IsMine)
        {
            horizontal = Input.GetAxis("Horizontal");
            vertical = Input.GetAxis("Vertical");

            // ï¿½Jï¿½ï¿½ï¿½ï¿½ï¿½Ì‰ï¿½]ï¿½pï¿½Ìæ“¾
            float cameraRotateX = Camera.main.transform.localEulerAngles.x;

            //ï¿½Eï¿½rï¿½ÌƒIï¿½uï¿½Wï¿½Fï¿½Nï¿½gï¿½æ“¾
            GameObject rightarm = transform.Find("RightArm").gameObject;

            // ï¿½Jï¿½ï¿½ï¿½ï¿½ï¿½Ì‰ï¿½]ï¿½pï¿½Æ‰Eï¿½rï¿½Ì‰ï¿½]ï¿½pï¿½ğ“¯Šï¿½
            rightarm.transform.localEulerAngles = new Vector3(cameraRotateX * -1 + 90, -90.0f, -90.0f);

            // ï¿½Jï¿½ï¿½ï¿½ï¿½ï¿½Ì‰ï¿½]ï¿½pï¿½Ìæ“¾
            float cameraRotateY = Camera.main.transform.localEulerAngles.y;

            // ï¿½Jï¿½ï¿½ï¿½ï¿½ï¿½Ì‰ï¿½]ï¿½pï¿½Æƒvï¿½ï¿½ï¿½Cï¿½ï¿½ï¿½[ï¿½Ì‰ï¿½]ï¿½pï¿½ğ“¯Šï¿½
            this.transform.localEulerAngles = new Vector3(0.0f, cameraRotateY - 90.0f, 0.0f);

            if (Input.GetAxisRaw("Jump") != 0.0f && playerState == TestHeat.PLAYER_STATE.ARIVE)
            {
                 jumpFlag = true;
            }
        }
    }

    private void FixedUpdate()
    {
        if (photonView.IsMine)
        {
            SetLocalGravity();

            //ï¿½Ú“ï¿½ï¿½ï¿½ï¿½ï¿½
            if (horizontal != 0 || vertical != 0)
            {
                if (playerState == TestHeat.PLAYER_STATE.ARIVE)
                {
                    // Rigidbodyï¿½Å‚ÌˆÚ“ï¿½(ï¿½Lï¿½[ï¿½ğ—£‚ï¿½ï¿½ï¿½ï¿½ï¿½áŠ±ï¿½ï¿½ï¿½ï¿½)
                    //moveDirection = speed * new Vector3(vertical, 0.0f, -horizontal).normalized;
                    //moveDirection = transform.TransformDirection(moveDirection);
                    //rb.MovePosition(rb.position + moveDirection * Time.fixedDeltaTime);

                    moveDirection = new Vector3(vertical, 0.0f, -horizontal).normalized;
                    transform.Translate(moveDirection.x / speed, 0.0f, moveDirection.z / speed);
                }
            }
            else if (isGround == true)
            {
                StopMove();
            }

            // ï¿½Wï¿½ï¿½ï¿½ï¿½ï¿½vï¿½ï¿½ï¿½ï¿½
            if (jumpFlag == true)//ï¿½ï¿½ï¿½nï¿½ï¿½ï¿½Ä‚ï¿½ï¿½ï¿½Æ‚ï¿½
            {
                jumpFlag = false;
                OnJump();
            }
        }
    }

    void OnCollisionEnter(Collision other) //ï¿½nï¿½Ê‚ÉGï¿½ê‚½ï¿½ï¿½ï¿½Ìï¿½ï¿½ï¿½
    {
        if (other.gameObject.tag == "Ground") //Groundï¿½^ï¿½Oï¿½ÌƒIï¿½uï¿½Wï¿½Fï¿½Nï¿½gï¿½ÉGï¿½ê‚½ï¿½Æ‚ï¿½
        {
            isGround = true; //isGroundï¿½ï¿½trueï¿½É‚ï¿½ï¿½ï¿½
        }
    }

    void SetLocalGravity()
    {
        rb.AddForce(localGravity, ForceMode.Acceleration);
    }

    void StopMove()
    {
        rb.velocity = Vector3.zero;
        rb.angularVelocity = Vector3.zero;
    }

    // Jump for new input system as old one is not working 
    private void OnJump()
    {
        if (playerState == TestHeat.PLAYER_STATE.ARIVE)
        {
            if (isGround == true)
            {
                isGround = false;
                rb.AddForce(new Vector3(0, jumpPower, 0));
            }
        }
    }

    public void SetPlayerState(TestHeat.PLAYER_STATE nowState)
    {
        playerState = nowState;
    }


}    


